### PR TITLE
Updated to euclid 0.22 and lyon_geom 0.16

### PR DESCRIPTION
**Pull request by avr1254**
Sorry about accidentally removing the last pull request. I split it into two commits, one to update the crate, and the other to format the source code.

### CODE REVIEW

**Comment by avr1254** [comment]
@jdm  Sorry to be a bother, but do you think we could merge this? It's an important step to upgrading to euclid 0.22.

**Comment by jdm** [comment]
I don't have merge access for this repository. In any case, typically we would wait to merge PRs like this one until the Servo PR is ready, because it tends to block any other fixes.

**Comment by parasyte** [comment]
Is there anything that can be done to unblock this PR? A few conflicts need to be resolved, but getting the dependencies updated is something I'm interested in for the `pixels` example with `raqote`.

**Comment by jrmuizel** [comment]
I've landed 74f0afa2be54561c1a9928e885ab95e8a4c5322d which is a version of this without the formatting changes.

**Comment by jiyinyiyong** [comment]
lyon has upgraded `0.17.x` to https://github.com/nical/lyon/commits/master . will this library upgrade newer versions of lyon?

**Comment by jrmuizel** [comment]
Yes

**Pull request closed without merging**
