### PR TITLE
Small refactor in blitter.rs to remove unsafe blocks

### PR DESCRIPTION
**Pull request by alex**
I wasn't sure if these were for performance (to avoid bounds checks), but in the absence of a comment to that effect I think removing the unsafe was a good idea :-)

### CODE REVIEW

**Comment by jrmuizel** [comment]
Thanks for the contribution.

The code here is pretty performance critical and this patch does add bounds checks into the inner loop so I'm inclined to not accept it.

This function is basically a direct port of some C++ code so that's why it's written in such a weird way. I think it might be possible to rewrite it in way so that the bounds check only happens at the beginning of the function, but I haven't thought about it that much yet.

**Comment by jrmuizel** [comment]
Here's a version that helps but I think we could probably still do better:
```rust
        y -= self.y;
        x1 -= self.x;
        x2 -= self.x;
        x2 = x2.min(self.width * SCALE);
        let max: u8 = ((1 << (8 - SHIFT)) - (((y & MASK) + 1) >> SHIFT)) as u8;
        let start = (y / 4 * self.width + (x1 >> SHIFT)) as usize;

        let mut fb = x1 & SUPER_MASK;
        let fe = x2 & SUPER_MASK;
        let mut n = ((x2 >> SHIFT) - (x1 >> SHIFT) - 1);
        let mut b = &mut self.buf[start..];


        // invert the alpha on the left side
        if n < 0 {
            b[0] = saturated_add(b[0], coverage_to_partial_alpha(fe - fb));
        } else {
            fb = (1 << SHIFT) - fb;
            b[0] = saturated_add(b[0], coverage_to_partial_alpha(fb));
            for i in &mut b[1..n as usize] {
                *i += max;
            }
            b[n as usize] = saturated_add(b[n as usize], coverage_to_partial_alpha(fe));
        }
```

**Comment by alex** [comment]
Perhaps something like:

```rust
        // invert the alpha on the left side
        if n < 0 {
            let mut b = &mut self.buf[start..];
            b[0] = saturated_add(b[0], coverage_to_partial_alpha(fe - fb));
        } else {
            fb = (1 << SHIFT) - fb;
            let mut b = &mut self.buf[start..start+n as usize];
            b[0] = saturated_add(b[0], coverage_to_partial_alpha(fb));
            for i in &mut b[1..] {
                *i += max;
            }
            b[n as usize] = saturated_add(b[n as usize], coverage_to_partial_alpha(fe));
        }
```

Untested, but that should get you down to just a single bounds check, I'd think?

**Comment by jrmuizel** [comment]
I think there are bugs in the above. Here's what I have now. It still has two index bounds checks when we construct the two slices but I think it's more conceivable that the compiler could eliminate the second set.
```rust
        y -= self.y;
        x1 -= self.x;
        x2 -= self.x;
        x2 = x2.min(self.width * SCALE);
        let max: u8 = ((1 << (8 - SHIFT)) - (((y & MASK) + 1) >> SHIFT)) as u8;
        let start = (y / 4 * self.width) as usize;

        let mut fb = x1 & SUPER_MASK;
        let fe = x2 & SUPER_MASK;
        let mut n = ((x2 >> SHIFT) - (x1 >> SHIFT) - 1);
        let mut b = &mut self.buf[start + (x1 >> SHIFT) as usize..start + (x2 >> SHIFT) as usize + 1];
        let len = b.len();

        // invert the alpha on the left side
        if len == 0 {
        } else if len == 1 {
            b[0] = saturated_add(b[0], coverage_to_partial_alpha(fe - fb));
        } else {
            fb = (1 << SHIFT) - fb;
            b[0] = saturated_add(b[0], coverage_to_partial_alpha(fb));
 
            for i in &mut b[1..len-1] {
                *i += max;
            }
            b[len-1] = saturated_add(b[len-1], coverage_to_partial_alpha(fe));
        }
```

**Comment by jrmuizel** [comment]
I landed a version of this in https://github.com/jrmuizel/raqote/commit/4fb5433521b7e25ecfd70fba00f9ab9a010d7b7a

**Comment by alex** [comment]
Great!

**Pull request closed without merging**
