### PR TITLE
Add a way to construct a PathBuilder back from a Path

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by jrmuizel** [comment]
What's the motivation for this?

**Comment by Eijebong** [comment]
Servo, it has a function I needed to implement for the raqote backend that would do exactly that. Unfortunately, path is private within PathBuilder so I had to add something here

**Comment by jrmuizel** [comment]
Can you elaborate on what Servo needs it for? or point me at some code that would use it?

**Comment by Eijebong** [comment]
https://github.com/servo/servo/pull/23936/files#diff-85c5c1b92bcc6126c8482505df99f8c0R191 Here's where I use it.

https://github.com/servo/servo/blob/6a637ceffbe34474ea4b657b08acc0966dc8a088/components/canvas/canvas_data.rs#L709 Here's where it's called from

**Pull request merged**
