### PR TITLE
Make DrawTarget backing storage generic

### PR DESCRIPTION
**Pull request by danieldg**
Fixes https://github.com/jrmuizel/raqote/issues/166.

### CODE REVIEW

**Comment by jrmuizel** [comment]
I'll try to take a look at this tomorrow.

**Comment by l4l** [comment]
Also note that the crate version should be bumped since it's a breaking change.

**Comment by danieldg** [comment]
> Also note that the crate version should be bumped since it's a breaking change.

Not due to this change - https://doc.rust-lang.org/stable/cargo/reference/semver.html#generic-new-default

However, there is an existing need to bump to 0.9 due to euclid's API change in 74f0afa2be54561c1a9928e885ab95e8a4c5322d

**Comment by l4l** [comment]
Ohhh, my bad, sorry for misinformation. And thanks for the link, haven't seen it yet, looks really helpful.

**Pull request merged**
